### ISSUE TITLE
Paquetes para instalar los modulos

### ISSUE THREAD

**Issue by V3ct0r** [satanas/workout#1]
Hola buenas noches, podrías colocar los paquetes necesarios para poder ejecutar workout? yo estoy usando debian jessie, muchas gracias.

**Comment by satanas** [comment]
Hola @V3ct0r, acabo de agregar el [readme](https://github.com/satanas/workout/blob/master/README.md) con las dependencias. Para Debian Jessie debería bastar con algo como:

``` bash
apt-get install python-gst-1.0 python-gtk2
```

Saludos

**Comment by V3ct0r** [comment]
Muchas gracias por tu ayuda @satanas pero quisiera preguntarte otra cosa:
Si yo estoy corriendo la aplicación en un entorno virtual porque no funciona?

Te dejo la versión de python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Y la salida cuando lo ejecuto en el entorno virtual
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    import gtk
ImportError: No module named gtk

De todas maneras fuera del entorno funciona perfectamente :+1:
